In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
fastball_speed = np.random.randint(90,106, size =500)

In [7]:
tommy_john = np.where(fastball_speed > 96, np.random.choice([0,1], size=500, p=[0.3, 0.7]), 0)


In [8]:
d = {'fastball_speed':fastball_speed, 'tommy_john': tommy_john}

In [9]:
df = pd.DataFrame(d)

In [10]:
df

fastball_speed  tommy_john
0                96           0
1                93           0
2               102           1
3               104           1
4               100           0
..              ...         ...
495             104           1
496              92           0
497             101           1
498              90           0
499              93           0

[500 rows x 2 columns]

In [11]:
X = df[['fastball_speed']]

In [12]:
y = df[['tommy_john']]

In [13]:
#normal train test split

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=11)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr = LogisticRegression()

In [19]:
lr.fit(X_train,y_train.values.ravel())

LogisticRegression()

In [20]:
lr.score(X_test, y_test)

0.71

In [21]:
#Test again

In [22]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X,y, test_size=0.2, random_state=25)

In [23]:
lr.fit(X2_train,y2_train.values.ravel())

LogisticRegression()

In [24]:
lr.score(X2_test, y2_test)

0.8

In [25]:
#Basic cross val

In [26]:
from sklearn.model_selection import cross_val_score

In [27]:
cvscore = cross_val_score(lr, X,y.values.ravel(),cv=10) #We'll get 10 results from this

In [28]:
cvscore

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [29]:
np.average(cvscore)

0.756

In [30]:
np.std(cvscore)

0.04270831300812523

In [32]:
#kfold example, define standard kfold

In [33]:
from sklearn.model_selection import KFold

In [35]:
kf = KFold(n_splits = 15, shuffle = True, random_state=42) #How many splits??

In [36]:
kfscore = cross_val_score(lr, X, y.values.ravel(), cv=kf, scoring='f1')

In [37]:
kfscore2 = cross_val_score(lr, X, y.values.ravel(), cv=kf, scoring='accuracy')

In [38]:
kfscore

array([0.66666667, 0.82758621, 0.72727273, 0.7027027 , 0.6875    ,
       0.72727273, 0.74074074, 0.72      , 0.66666667, 0.60869565,
       0.66666667, 0.63157895, 0.64516129, 0.66666667, 0.6       ])

In [39]:
np.average(kfscore)

0.6856785107611354

In [40]:
kfscore2

array([0.76470588, 0.85294118, 0.82352941, 0.67647059, 0.70588235,
       0.81818182, 0.78787879, 0.78787879, 0.78787879, 0.72727273,
       0.72727273, 0.78787879, 0.66666667, 0.78787879, 0.63636364])

In [41]:
np.average(kfscore2)

0.7559120617944146

In [42]:
np.std

<function std at 0x000001F5EE3D5CF0>

In [43]:
np.std(kfscore)

0.05620337068328653

In [44]:
np.std(kfscore2)

0.060970963505883366

In [45]:
#Stratified k fold

In [46]:
from sklearn.model_selection import StratifiedKFold

In [49]:
kf3 = StratifiedKFold(n_splits=10, shuffle= True, random_state=11)

In [51]:
kfscore3 = cross_val_score(lr,X,y.values.ravel(), cv = kf3)

In [52]:
kfscore3

array([0.66, 0.76, 0.76, 0.8 , 0.8 , 0.74, 0.76, 0.74, 0.78, 0.76])

In [53]:
kfscore3.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [54]:
np.average(kfscore3)

0.756

In [55]:
np.std(kfscore3)

0.03773592452822642

In [56]:
#pipeline example

In [57]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaler = StandardScaler()

In [59]:
from sklearn.pipeline import make_pipeline

In [60]:
pipe1 = make_pipeline(scaler,lr)

In [61]:
pipe1.fit(X_train, y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [62]:
scorespipe = cross_val_score(pipe1, X, y.values.ravel(), cv = 10)

In [63]:
scorespipe

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [66]:
np.average(scorespipe)

0.756

In [67]:
np.std(scorespipe)

0.04270831300812523