In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
miles = pd.DataFrame({'farthest_run_mi':[50,62, np.nan,100,26,13,31,50]})

In [9]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imp_mean = SimpleImputer(strategy='mean')

In [12]:
imp_mean

SimpleImputer()

In [13]:
imp_mean.info()

AttributeError: 'SimpleImputer' object has no attribute 'info'

In [14]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [15]:
imp_median = SimpleImputer(strategy='median') 

In [16]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [17]:
miles

farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [20]:
imp_mode = SimpleImputer(strategy='most_frequent')

In [21]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [23]:
imp_constant = SimpleImputer(strategy='constant',fill_value=13)

In [24]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [26]:
names = pd.DataFrame({'names':['lorenzo','nolan','axel','marquitos',np.nan,'robinho']})

names

In [27]:
names

names
0    lorenzo
1      nolan
2       axel
3  marquitos
4        NaN
5    robinho

In [28]:
imp_constant_cat = SimpleImputer(strategy = 'constant',  fill_value = 'Missing')

In [29]:
imp_constant_cat.fit_transform(names)

array([['lorenzo'],
       ['nolan'],
       ['axel'],
       ['marquitos'],
       ['Missing'],
       ['robinho']], dtype=object)

In [32]:
imp_mean_market = SimpleImputer(strategy = 'mean', add_indicator = True)

In [33]:
imp_mean_market.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [34]:
data = {
    'Nombre': ['Ana', 'Luis', 'Juan', 'Carla', 'Pedro', 'Sofia', 'Diego', 'Martina', 'Lucas', 'Valeria', 
               'Fernando', 'Lucia', 'Jorge', 'Maria', 'Pablo', 'Andres', 'Paula', 'Gonzalo', 'Micaela', 'Nicolas'],
    'Millas_Corridas': [50, 42, np.nan, 60, 55, 38, 70, np.nan, 44, 52, 60, 48, np.nan, 40, 35, np.nan, 61, 47, 39, 62]
}


In [35]:
df1 = pd.DataFrame(data = data)

In [36]:
df1

Nombre  Millas_Corridas
0        Ana             50.0
1       Luis             42.0
2       Juan              NaN
3      Carla             60.0
4      Pedro             55.0
5      Sofia             38.0
6      Diego             70.0
7    Martina              NaN
8      Lucas             44.0
9    Valeria             52.0
10  Fernando             60.0
11     Lucia             48.0
12     Jorge              NaN
13     Maria             40.0
14     Pablo             35.0
15    Andres              NaN
16     Paula             61.0
17   Gonzalo             47.0
18   Micaela             39.0
19   Nicolas             62.0

In [39]:
import numpy as np
from sklearn.impute import SimpleImputer

In [54]:
imputer_cons = SimpleImputer(strategy = 'constant',fill_value = '10', add_indicator = True)

In [55]:
imputer_cons.fit_transform(df1)

array([['Ana', 50.0, False],
       ['Luis', 42.0, False],
       ['Juan', '10', True],
       ['Carla', 60.0, False],
       ['Pedro', 55.0, False],
       ['Sofia', 38.0, False],
       ['Diego', 70.0, False],
       ['Martina', '10', True],
       ['Lucas', 44.0, False],
       ['Valeria', 52.0, False],
       ['Fernando', 60.0, False],
       ['Lucia', 48.0, False],
       ['Jorge', '10', True],
       ['Maria', 40.0, False],
       ['Pablo', 35.0, False],
       ['Andres', '10', True],
       ['Paula', 61.0, False],
       ['Gonzalo', 47.0, False],
       ['Micaela', 39.0, False],
       ['Nicolas', 62.0, False]], dtype=object)

In [51]:
from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (imputer_cons, ['Nombre']),
    (imp_mean, ['Millas_Corridas']),
    reminder='drop'
)