In [1]:
import torch

In [2]:
import numpy as np

In [3]:
tensor_1 = torch.tensor([1,2,3])
print("Probando Tensores: ", tensor_1)

Probando Tensores:  tensor([1, 2, 3])


In [4]:
array_1 = np.array([1,2,3])

In [5]:
tensor_from_numpy = torch.tensor(array_1)

In [6]:
print("Pytorch sensor from numpy array: ", tensor_from_numpy)

Pytorch sensor from numpy array:  tensor([1, 2, 3], dtype=torch.int32)


In [7]:
empty_tensor = torch.empty(3)

In [8]:
print("Empty tensor", empty_tensor)

Empty tensor tensor([0., 0., 0.])


In [10]:
zero_tensor = torch.zeros(2,3)
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
one_tensor = torch.ones(2,3)
print(one_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
random_tensor = torch.rand(3,3)

In [14]:
print(random_tensor)

tensor([[0.9473, 0.6870, 0.8589],
        [0.8128, 0.3119, 0.8751],
        [0.4983, 0.9844, 0.1454]])


In [15]:
arange_tensor = torch.arange(start=0,end=100, step=10)

In [16]:
print(arange_tensor)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [18]:
random_tensor[0,1]

tensor(0.6870)

In [19]:
random_tensor[1, :]

tensor([0.8128, 0.3119, 0.8751])

In [20]:
reshape_tensor = torch.rand(5,4)

In [21]:
print(reshape_tensor)

tensor([[0.4930, 0.6670, 0.0968, 0.4668],
        [0.5788, 0.2150, 0.8838, 0.6925],
        [0.5907, 0.0948, 0.2102, 0.2874],
        [0.4396, 0.0459, 0.3422, 0.4214],
        [0.0205, 0.4575, 0.1493, 0.3906]])


In [22]:
new_reshape_tensor = reshape_tensor.view(-1,2)

In [23]:
print(new_reshape_tensor)

tensor([[0.4930, 0.6670],
        [0.0968, 0.4668],
        [0.5788, 0.2150],
        [0.8838, 0.6925],
        [0.5907, 0.0948],
        [0.2102, 0.2874],
        [0.4396, 0.0459],
        [0.3422, 0.4214],
        [0.0205, 0.4575],
        [0.1493, 0.3906]])


In [25]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([2,4,6])

results_add_1 = torch.add(tensor_b,tensor_a)
results_add_2 = torch.add(tensor_a,tensor_b)
results_sub_1 = tensor_b - tensor_a

print(results_add_1)
print(results_add_2)
print(results_sub_1)

tensor([3, 6, 9])
tensor([3, 6, 9])
tensor([1, 2, 3])


In [26]:
tensor_b.add_(tensor_a)

tensor([3, 6, 9])

In [27]:
tensor_b

tensor([3, 6, 9])

In [28]:
matrix_a = torch.tensor([[1,2], [3,4]])
matrix_b = torch.tensor([[5,6], [7,8]])

In [29]:
matrix_a

tensor([[1, 2],
        [3, 4]])

In [30]:
matrix_b

tensor([[5, 6],
        [7, 8]])

In [31]:
results_multiply = torch.mm(matrix_a,matrix_b)

In [32]:
print(results_multiply)

tensor([[19, 22],
        [43, 50]])


In [33]:
results_multiply_2 = torch.mul(matrix_a,matrix_b)

In [34]:
print(results_multiply_2)

tensor([[ 5, 12],
        [21, 32]])


In [35]:
random_tensor.dtype

torch.float32

In [39]:
tensor_int = torch.tensor([4,5,6], dtype=torch.int64)

In [40]:
print(tensor_int)

tensor([4, 5, 6])


In [41]:
print(tensor_int.dtype)

torch.int64


In [42]:
tensor_int.device

device(type='cpu')

In [43]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [45]:
tensor_int.to(device)

tensor([4, 5, 6])

In [46]:
tensor_int.device

device(type='cpu')

In [47]:
torch.cuda.device_count()

0

In [48]:
tensor_new = torch.tensor([51,50,46,2], dtype=torch.float32, device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [50]:
print(torch.cuda.is_available())  # Devuelve True si CUDA está disponible, de lo contrario False


False
